Centralize the rootContainer and Worked on the FIlter Panel
intermine/bluegenes-go-term-visualizer pull request #19
Opened 2020-03-23 11:17 UTC by egbobright

Increased the width of the id yourDiv from 60% to 90%. This helped clear out the jumbled figures in the chart.
 2. Centralize the rootContainer by applying the margin-left property. This should make it more visible and accessible.
 3. Worked on the Filter Panel by:
 a. changing the background color and the text color. 
b. changing the Results length and 
c. applied border-radius accross all select and input tag.

2020-03-23 16:14 UTC, uosl commented
This is a great start, but I'm not a fan of the new background colour and button hover colour (there's too much contrast compared to the rest of the elements).

I was also hoping to see a different layout of the filter panel. I think it can be made more compact, perhaps like this (I moved things around in gimp). Do you think you could work on this?

![compact-filter-panel](https://user-images.githubusercontent.com/3865590/77337697-275d5d80-6d21-11ea-89a3-23c37e6a8291.png)

2020-03-23 16:19 UTC, egbobright commented
OK. I'll work on the Filter Panel again.

Thank you for the feedback.

On 23 Mar 2020 17:15, "Herald" <notifications@github.com> wrote:

> This is a great start, but I'm not a fan of the new background colour and
> button hover colour (there's too much contrast compared to the rest of the
> elements).
>
> I was also hoping to see a different layout of the filter panel. I think
> it can be made more compact, perhaps like this (I moved things around in
> gimp). Do you think you could work on this?
>
> [image: compact-filter-panel]
> <https://user-images.githubusercontent.com/3865590/77337697-275d5d80-6d21-11ea-89a3-23c37e6a8291.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/intermine/bluegenes-GO-term-visualizer/pull/19#issuecomment-602702595>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK3J2YKDYXKWKCNIEE2YYVLRI6DI7ANCNFSM4LRZKUPQ>
> .
>

2020-03-26 15:08 UTC, egbobright commented
Kindly check the improvement on the pull request I made earlier.
I have reverted to the original background color but I worked on the display property in order to bring it close to gimp prototype.

2020-03-26 15:12 UTC, egbobright commented
This is how it looks now:
![new_go_term](https://user-images.githubusercontent.com/45522273/77662780-97b3eb00-6f7c-11ea-800e-ba3e3e0695ae.PNG)

2020-03-27 17:04 UTC, heralden requested changes
It looks fine now! There's just one more thing before I merge this; please see my comment.

2020-03-27 17:04 UTC, uosl commented on src/style.less
> +		margin-left: 105px;
This visualization is for use in Bluegenes, so the extra margin would add a lot of empty space when the viz is displayed inside Bluegenes. I agree that it makes it nicer to look at when running `npm run dev`, but a nicer displayer for each of the tools is something we want to work on in the future.

Sorry that this hasn't been specified properly!

To summarise, please remove the margin-left property.

2020-03-28 06:22 UTC, egbobright commented
Many thanks for your review. The change has been implemented on the rootContainer class.

2020-03-30 10:31 UTC, heralden approved these changes
Thank you for your contribution!

2020-03-30 10:31 UTC, merged